#!/usr/bin/env python3
"""
Render results.jsonl into a table, and write it into RESULTS.md.

Compares every measured number against the modelled estimate from the audit, so
the point of Phase 0 - replacing guesses with measurements - is visible at a
glance.

Usage
-----
    python report.py
    python report.py --results results.jsonl --out RESULTS.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Modelled estimates from docs/plan.md section "Where the seconds go".
MODELLED = {
    "transcript": 1.08,
    "native": 1.13,
    "nllb": 2.23,
}

HEADER = """# Phase 0 results

Generated by `report.py` from `results.jsonl`. Do not edit by hand above the
notes section - re-run the sweep instead.

Latency is measured mouth-to-screen: for every newly committed segment,
`wall_clock_since_stream_start - audio_end_time_of_that_segment`, with the audio
streamed at exactly 1x. Commits arriving after end-of-audio are excluded.

"""

FOOTER_TEMPLATE = """
## What this tells us

Fill these in once the sweep has run. They are the Phase 0 exit criteria.

- [ ] **Measured latency vs the estimate.** Modelled was ~1.1 s transcript,
      ~2.2 s NLLB. Actual: ______
- [ ] **VRAM for SimulStreaming large-v3.** UFAL recommend >=10 GB. Actual: ______ MiB.
      If it is well under, the 3070 may carry the whole project.
- [ ] **medium vs large-v3, by ear, on French and English.** If medium is good
      enough, the hardware question mostly dissolves. Verdict: ______
- [ ] **Is native FR->EN meaningfully faster than NLLB FR->EN?** Compare
      `native-en/fr-en-native` against `nllb/fr-en-nllb`. Delta: ______
- [ ] **Can one server serve both paths?** Did `mixed-paths` produce sane output
      for both runs, or did one of them fail / come back empty? Answer: ______
- [ ] **Where does NLLB load - GPU or CPU?** Compare the VRAM delta of `large-simul`
      against `nllb`. Answer: ______
- [ ] **Does `auto` language detection hold, or flip mid-stream?** Answer: ______

## Decisions taken

- Default model: ______
- Default backend / policy: ______
- Default frame-threshold: ______
- Build target GPU: ______
- Dual-pane (source + translation) or translation-only: ______
"""


def fmt(value, suffix="s") -> str:
    if value is None:
        return "-"
    return f"{value:.2f}{suffix}"


def load(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(f"No results at {path}. Run .\\sweep.ps1 first.")
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def classify(row: dict) -> str:
    label = row.get("label", "")
    if "native" in label:
        return "native"
    if row.get("target_language"):
        return "nllb"
    return "transcript"


def build_table(rows: list[dict]) -> str:
    out = [
        "| run | pair | n | median | p90 | max | vs modelled | first text |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        stats = row.get("stats", {})
        kind = classify(row)
        # Report the stream that actually carries the user-visible output.
        primary = "translation" if stats.get("translation", {}).get("n") else "transcript"
        s = stats.get(primary, {})
        if not s.get("n"):
            out.append(f"| `{row.get('label','?')}` | {primary} | 0 | - | - | - | - | - |")
            continue

        expected = MODELLED[kind]
        delta = s["median"] - expected
        sign = "+" if delta >= 0 else ""
        pair = f"{row.get('language')}&rarr;{row.get('target_language') or row.get('language')}"

        out.append(
            f"| `{row.get('label','?')}` | {pair} ({primary}) | {s['n']} | "
            f"**{fmt(s['median'])}** | {fmt(s['p90'])} | {fmt(s['max'])} | "
            f"{sign}{delta:.2f}s | {fmt(row.get('first_text_at'))} |"
        )
    return "\n".join(out)


def build_split_table(rows: list[dict]) -> str:
    """Transcript vs translation side by side - this is where the sentence gate shows."""
    interesting = [r for r in rows if r.get("stats", {}).get("translation", {}).get("n")]
    if not interesting:
        return ""
    out = [
        "",
        "## Transcript vs translation, same run",
        "",
        "If NLLB is sentence-gated, the translation median sits well above the",
        "transcript median in the same run. That gap is the sentence gate, measured.",
        "",
        "| run | transcript median | translation median | gap |",
        "|---|---:|---:|---:|",
    ]
    for row in interesting:
        t = row["stats"]["transcript"]
        x = row["stats"]["translation"]
        gap = (x["median"] - t["median"]) if (t.get("median") and x.get("median")) else None
        out.append(
            f"| `{row.get('label','?')}` | {fmt(t.get('median'))} | "
            f"**{fmt(x.get('median'))}** | {fmt(gap)} |"
        )
    return "\n".join(out)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--results", default="results.jsonl")
    p.add_argument("--out", default="RESULTS.md")
    args = p.parse_args()

    rows = load(Path(args.results))
    body = HEADER + build_table(rows) + "\n" + build_split_table(rows) + "\n" + FOOTER_TEMPLATE

    Path(args.out).write_text(body, encoding="utf-8")
    print(body)
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
